jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver lts-12"
      stack-lts-14:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver lts-14"
      stack-nightly:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver nightly"
    maxParallel: 3
  steps:
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -skL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps wai-handler-launch
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
