jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver lts-12"
      stack-lts-14:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver lts-14"
      nightly:
        BUILD: stack
        STACK_YAML: stack-nightly.yaml
        ARGS: "--resolver nightly"
    maxParallel: 6
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps wai-handler-launch
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
